- name: 1st conf
  hosts: all
  become: yes
  vars_files:
    - vars/variables.yml
  gather_facts: yes
  roles:
    - docker

- name: 2nd conf
  hosts: portainer
  become: yes
  vars_files:
    - vars/variables.yml
  gather_facts: yes
  roles:
    - portainer
